#!/usr/bin/env python3

BYTE_LIMIT = 254

MAC_ADDRESS_BYTES = 12
TIMESTAMP_BYTES = 10
SEQUENCE_NUMBER_BYTES = 4

PREFIX_BYTES = MAC_ADDRESS_BYTES + TIMESTAMP_BYTES + SEQUENCE_NUMBER_BYTES
PAYLOAD_BYTES = BYTE_LIMIT - PREFIX_BYTES
